version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version you are using
    commands:
      - echo "Installing dependencies..."
      #- mkdir python-layer
  build:
    commands:
      - echo "Zipping the layer content..."
      - cd python-layer
      - pip3 install pandas -t .
      - zip -r gonzo-cfnresponse.zip . || { echo "Zip command failed"; exit 1; }
      - ls -la
      - echo "Running build..."
      - sam build --template-file ../template.yaml
      - ls -la
      - echo "Running deploy..."
      - sam package --output-template-file packaged.yaml --resolve-s3 --template-file template.yaml
      - ls -l ./python-layer/gonzo-cfnresponse.zip

      - pwd
      - sam deploy --resolve-s3 --stack-name gonzo-cfnresponse --capabilities CAPABILITY_IAM

# artifacts:
#   type: zip
#   files:
#     - '**/*' 
#   base-directory: '.aws-sam/build'
