version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify your Python version
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t ./layer/python  # Ensure this is correct for your structure

  pre_build:
    commands:
      - echo "Listing contents of the layer directory before zipping..."
      - ls -la layer  # Check what is in the layer directory
      - echo "Zipping the layer content..."
      - cd layer
      - zip -r ../lambda-layer.zip python/  # Zip the contents of the 'python' directory and place it at the root
      - echo "Listing contents of the parent directory after zipping..."
      - ls -la ../  # Check that lambda-layer.zip exists in the parent directory

  build:
    commands:
      - echo "Packaging the SAM application"
      - ls -la  # List files in the current directory to check for the presence of lambda-layer.zip
      - sam package --output-template-file packaged.yaml --resolve-s3 --template-file template.yaml

artifacts:
  files:
    - packaged.yaml
